In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,4]
a= np.array(list1)
a

array([1, 2, 3, 4])

In [3]:
a.shape

(4,)

In [4]:
b= np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b)
print(b[1][1])
print(b[1,1])

(2, 3)
[[1 2 3]
 [4 5 6]]
5
5


In [5]:
#백터화 연산 #개념 : 배열의 각 요소에 대한 반복 연산을 하나의 명령으로 # 백터화 연산을 하지 않은 일반적인 반복문은 연산(속도 느림)

In [5]:
data=[1,2,3,4,5]
ans=[]
for i in data:
    ans.append(2*i)
print(ans) #list
x= np.array(data)
print(x*2) # array

[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


In [7]:
a=np.array([1,2,3])
b=np.array([10,20,30])
(a==2)&(b>10)

array([False,  True, False])

In [10]:
print(a.shape)
print(a.ndim)
print(type(a))
print(a.dtype)

(5, 5)
2
<class 'numpy.ndarray'>
float64


In [21]:
a=np.zeros(4) # [0,0,0,0]
print(a)
a= np.ones((2,4))
print(a)
a=np.full((3,2),2)
print(a)
a=np.eye(5) #단위행렬
print(a) 

[0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
a=np.array(range(20))
# print(a)
a=np.array(range(20)).reshape(4,5)
print(a)
print(len(a))
print(len(a[0]))
print(a.ndim) #2차 행렬 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
4
5
2


In [30]:
print(a)
print(a>10)
print(a[a>10])
a[a>10]=99
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 99 99 99 99]
 [99 99 99 99 99]]
[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]]
[99 99 99 99 99 99 99 99 99]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 99 99 99 99]
 [99 99 99 99 99]]


In [ ]:
##-------09-19

In [38]:
arr= np.arange(0,3*2*4)
print(len(arr))
print(arr)
v= arr.reshape(3,2,4)
print(v)
print(len(v))
print(len(v[0]))
print(len(v[0][0]))

24
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
3
2
4


In [42]:
a=np.arange(0,12)
print(a)
a=a.reshape(3,4)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [43]:
b= np.array([0,1,2,3,4])
print(b[-1])

4


다차원 배열을 슬라이싱 할 때 사용되는 콤마(,)로 차원을 구분(축)

In [46]:
print(a)
print(a[0,1])
print(a[-1,-1])
print(a[0, :])
# 두번째 열 전체를 추출

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
1
11
[0 1 2 3]


인덱싱 : 행 지정, 슬라이싱 : 추출 열 지정

In [ ]:
# 두번쨰 행의 두번쨰 열부터 끝까지 추출

In [51]:
print(a[1,1:])
print(a[:2,:])
print(a[1,:].shape)
print(a[1:2,:].shape)

[5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
(4,)
(1, 4)


리스트 -> np.array -> 배열 -> reshape -> 인덱싱
임의의 numpy배열 a에 대해, a[[row1,row2],[col1,col2]] 

In [61]:
a= np.array([[1,2],[3,4],[5,6]])
print(a)
print(a.shape)
print()
print(a[[0,1,2],[0,1,0]])
print(type(a[[0,1,2],[0,1,0]]))

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

[1 4 5]
<class 'numpy.ndarray'>


In [65]:
print(type(a[0,0]))
print(a[0,0])
s= a[[0,1],[1,1]]
print(s)

<class 'numpy.int32'>
1
[2 4]


부울린 값 참조

In [69]:
list = [[1,2,3],
       [4,5,6],
       [7,8,9]]
x= np.array(list)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
bool_ind_arr = np.array([
    [False,True,False],
    [True,False,True],
    [False,True,False]
])
print(bool_ind_arr)
print(type(bool_ind_arr))

[[False  True False]
 [ True False  True]
 [False  True False]]
<class 'numpy.ndarray'>


True 값들만 참조해서 2,4,6,8을 뽑아오고 싶다.

In [84]:

x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
res= x[bool_ind_arr] #1.
print(res) 
print(x[bool_ind_arr])#2.
print(x[x%2==0]) #3.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 4 6 8]
[2 4 6 8]
[2 4 6 8]
