In [4]:
# 집계함수 :axis(축)지정, 기본값(None)- 전체
#axis = 0, 행 기준으로 각각의 행에 대한 동일한 인덱스의 요소를 하나의 배열로 보고 집계 연산 수행
# axis =1, 열 기준으로 각각의 행에 대한 집계 연산 수행

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
a= np.arange(1,10).reshape(3,3)
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [20]:
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))
# print(a.sum(axis=1))

45
[12 15 18]
[ 6 15 24]


In [26]:
print(np.max(a))
print(np.max(a,axis=0))
print(np.max(a,axis=1))
print(np.cumsum(a)) #누적합계
print(np.cumsum(a,axis=0))
print(np.median(a))
print(np.median(a,axis=1))

9
[7 8 9]
[3 6 9]
[ 1  3  6 10 15 21 28 36 45]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


5.0
[2. 5. 8.]
