slicing indexing 파일 읽어 들이고, 

In [2]:
import numpy as np

In [6]:
a1=np.arange(24)
a2=np.arange(24).reshape((4,6))
a3=np.arange(24).reshape((2,4,3))
print(a1)
print()
print(a2)
print()
print(a3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [8]:
a1[5] = 1000
a2[0,1] = 1000
a3[1,0,1] = 1000

In [11]:
print(a1)
print(a2)
print(a3)

[   0    1    2    3    4 1000    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23]
[[   0 1000    2    3    4    5]
 [   6    7    8    9   10   11]
 [  12   13   14   15   16   17]
 [  18   19   20   21   22   23]]
[[[   0    1    2]
  [   3    4    5]
  [   6    7    8]
  [   9   10   11]]

 [[  12 1000   14]
  [  15   16   17]
  [  18   19   20]
  [  21   22   23]]]


★문제 a2에서 7~10 , 13~16을 추출해서 출력

In [16]:
print(a2[1:3,1:-1])

[[ 7  8  9 10]
 [13 14 15 16]]


In [17]:
print(a2)
a2[:,1:3]=99
print(a2)

[[   0 1000    2    3    4    5]
 [   6    7    8    9   10   11]
 [  12   13   14   15   16   17]
 [  18   19   20   21   22   23]]
[[ 0 99 99  3  4  5]
 [ 6 99 99  9 10 11]
 [12 99 99 15 16 17]
 [18 99 99 21 22 23]]


In [22]:
a1=np.arange(1,25).reshape(4,6)
print(a1)
even_a=a1%2==0
print(a1[even_a])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[ 2  4  6  8 10 12 14 16 18 20 22 24]


------------------------------------------------PANDAS-------------------------------------------------- 

--------------------------------------------------09-07----------------------------------------------------

In [23]:
import pandas as pd

In [28]:
rain = pd.read_csv('seattle.csv')
# print(rain)

In [32]:
rain_r=rain['PRCP']
# print(rain_r)
rain_r=rain['PRCP'].values #values = numpy.array로 졍렬
rain_r

array([  0,  41,  15,   0,   0,   3, 122,  97,  58,  43, 213,  15,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   5,   0,   0,   0,   0,
         0,  89, 216,   0,  23,  20,   0,   0,   0,   0,   0,   0,  51,
         5, 183, 170,  46,  18,  94, 117, 264, 145, 152,  10,  30,  28,
        25,  61, 130,   3,   0,   0,   0,   5, 191, 107, 165, 467,  30,
         0, 323,  43, 188,   0,   0,   5,  69,  81, 277,   3,   0,   5,
         0,   0,   0,   0,   0,  41,  36,   3, 221, 140,   0,   0,   0,
         0,  25,   0,  46,   0,   0,  46,   0,   0,   0,   0,   0,   0,
         5, 109, 185,   0, 137,   0,  51, 142,  89, 124,   0,  33,  69,
         0,   0,   0,   0,   0, 333, 160,  51,   0,   0, 137,  20,   5,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  38,
         0,  56,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,  18,  64,   0,   5,  36,  13,   0,
         8,   3,   0,   0,   0,   0,   0,   0,  18,  23,   0,   

In [36]:
print(type(rain_r))
print('데이터 크기 :',len(rain_r))

<class 'numpy.ndarray'>
데이터 크기 : 365


In [41]:
#날짜 데이터 만큼 데이터 뽑아내기
days_a=np.arange(0,365)
con_jan=days_a<31 #True False 값
# print(days_a)
# print(con_jan)
# print(rain_r[con_jan])

1월달 강수량의 총합 np.sum, 평균 np.mean, 중앙값 np.median 

In [49]:
print(np.sum(rain_r[con_jan]))
print(np.mean(rain_r[con_jan]))

940
30.322580645161292


팬시 인덱싱 = 배열에 인덱스 배열을 전달해서 데이터 참조

In [60]:
a=np.arange(1,25).reshape((4,6))
print(a)
print(a[0,0],a[1,1],a[2,2],a[3,3])
print(a[[0,1,2,3],[0,1,2,3]])
print(a[:,[1,3]])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
1 8 15 22
[ 1  8 15 22]
[[ 2  4]
 [ 8 10]
 [14 16]
 [20 22]]


In [76]:
a=np.random.randint(1,10,(2,3))
print('a=',a)
# b=np.random.random((1,10))
# b
print(a.ravel())
print(np.ravel(a))

a= [[8 5 6]
 [7 2 6]]
[8 5 6 7 2 6]
[8 5 6 7 2 6]


배열 변경, 삭제, 추가...
resize : 배열크기변경(요소 수 변경), reshape : 배열변경(요소 수 변경 x)

In [82]:
a=np.random.randint(1,10,(2,6))
print(a)
print(a.reshape((3,4)))
print()
print(a.reshape(2,2,3))

[[1 7 1 9 1 8]
 [4 2 9 2 9 1]]
[[1 7 1 9]
 [1 8 4 2]
 [9 2 9 1]]

[[[1 7 1]
  [9 1 8]]

 [[4 2 9]
  [2 9 1]]]


In [86]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(10,19).reshape(3,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [92]:
res= np.append(a,b) # axis 지정안하면 1차원배열됨
print(res)
res1= np.append(a,b,axis=1)
print(res1)
print()
res2= np.append(a,b,axis=0)
print(res2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [98]:
res=np.arange(10,20).reshape(2,5)
print(res)
# a=np.append(a,res,axis=0) # 기준 축과 shape가 다르면 append시 오류 발생

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [134]:
x=np.arange(10,20).reshape(2,5)
print(np.append(x,res,axis=1))

[[10 11 12 13 14  1  2  3  7  8  9]
 [15 16 17 18 19  4  5  6 10 11 12]]


삽입 제거

In [135]:
a=np.arange(1,10).reshape(3,3)
b=np.insert(a,1,99,axis=1) # array(a)의 1번째 열에 99를 삽입
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1 99  2  3]
 [ 4 99  5  6]
 [ 7 99  8  9]]


a배열의 1번 인덱스 행 제거 & a배열의 1번 인덱스 열 제거

In [136]:
a=np.arange(1,10).reshape(3,3)
print(np.delete(a,1,axis=0))
print(np.delete(a,1,axis=1))

[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]


배열간에 결합 concatenate, vstack, hstack (배열까리 합쳐줌)

In [122]:
a= np.arange(1,7).reshape(2,3)
b= np.arange(7,13).reshape(2,3)
res= np.concatenate((a,b)) #2행3열 + 2행3열 => 4행3열
res

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [123]:
res= np.concatenate((a,b),axis=0)
print(res)
res= np.concatenate((a,b),axis=1)
print(res)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [131]:
a=np.arange(1,7).reshape(2,3)
b=np.arange(7,13).reshape(2,3)
print(np.vstack((a,b)))
print()
# print(np.vstack((a,b,a,b)))
print(np.hstack((a,b)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


배열 분리 hsplit( ,2) & vsplit( ,2) 2그룹으로 나눠라. 

In [141]:
a=np.arange(1,25).reshape(4,6)
res= np.hsplit(a,2)
print(a)
print(res)
res= np.vsplit(a,2)
print(res)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])]
[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]


내가 읽어오고 싶은 타입으로 변경 dtype , 타입 확인 할때도

In [151]:
x= np.array([1,2])
print(x.dtype)
x1= np.array([1,2],dtype=np.int64)
print(x1.dtype)

int32
int64


행렬과 백터의 곱 np.dot

In [157]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
v=np.array([9,10])
w=np.array([11,12])

In [158]:
print(x)
print()
print(np.dot(x,y))
print(x.dot(v))

[[1 2]
 [3 4]]

[[19 22]
 [43 50]]
[29 67]


백터의 내적

In [160]:
print(np.dot(v,w))
print(v.dot(w))

219
219


T속성 행렬 변환 .T

In [166]:
x=np.array([[1,2],[3,4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [184]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
y=np.empty_like(x) ##※x와 같은 형태로 비어있는 행렬만들기, 답은 이상
vv=np.tile(v,(4,1)) #v와 같은 array를 4행 1번반복

In [185]:
print(v)
print(vv)
print(y)

[1 0 1]
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [187]:
for i in range(4):
 y[i,:] = x[i,:]+v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [192]:
a=np.array([[1,2],[4,5]])
s=np.prod(a)
print(a)
print(s)
s1=np.prod(a,axis=0)
print(s1)
print()
s2=np.prod(a,axis=1)
print(s2)

[[1 2]
 [4 5]]
40
[ 4 10]

[ 2 20]
